-- Auth codes are stored in Redis with TTL-based expiration, not PostgreSQL.
--
-- Key format:  auth_code:{sha256_hex}
-- Value:       JSON { app_registration_id, entity_app_wallet_id, code_challenge, redirect_uri, state }
-- TTL:         Configurable via AUTH_CODE_TTL_SECS (default 30 seconds)
--
-- This migration intentionally left empty. The original auth.auth_codes table
-- has been replaced by Redis key-value storage. Expired codes are cleaned up
-- automatically by Redis TTL -- no background cleanup task is needed.
